site_name: PingouinMod API
site_description: Documentation de l'API PingouinMod

theme:
  name: material
  palette:
    # Dark mode by default
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Swith to dark mode
  features:
    - search.suggest
    - search.highlight
    - navigation.top

markdown_extensions:
  - tables
  - pymdownx.highlight
  - pymdownx.superfences