[ShortNaming]

; Each short name must be unique and map to a single full name.
; Format: ShortName = FullGamePath
; Dont forget that Blueprint classes need the _C suffix.

; Vehicles
CCFM=/Game/Wildfire/Blueprints/Core/Vehicles/CCF/BP_CCFM.BP_CCFM_C
DRAGON=/Game/Wildfire/Blueprints/Core/Vehicles/Helicopter_EC145/BP_MasterHelicopter.BP_MasterHelicopter_C
CAL34=/Game/Wildfire/Blueprints/Core/Vehicles/CalFire34/BP_CalFire34.BP_CalFire34_C

; Equipment
BACKPACKPUMP=/Game/Wildfire/Blueprints/Core/Items/BackpackPump/BP_BackpackPump.BP_BackpackPump_C
CHAINSAW=/Game/Wildfire/Blueprints/Core/Items/Chainsaw/BP_EquippableChainsaw.BP_EquippableChainsaw_C
DRIPTORCH=/Game/Wildfire/Blueprints/Core/Items/DripTorch/BP_DripTorch.BP_DripTorch_C
ESCAPEMASK=/Game/Wildfire/Blueprints/Core/Items/EscapeMask/BP_EscapeMaskPurse.BP_EscapeMaskPurse_C
FIREHOSE=/Game/Wildfire/Blueprints/Core/Items/FireHose/BP_EquippableFirehose.BP_EquippableFirehose_C 
; TODO : Add variants ? (There is a lot in the folder and its 01:45AM rn so ... lazy)
FLAMETHROWER=/Game/Wildfire/Blueprints/Core/Items/Flamethrower/BP_EquippableFlamethrower.BP_EquippableFlamethrower_C
FRAMEBACKPACK=/Game/Wildfire/Blueprints/Core/Items/FrameBackpack/BP_FrameBackpack.BP_FrameBackpack_C
MEDBACKPACK=/Game/Wildfire/Blueprints/Core/Items/MedBackpack/BP_MedBackpack.BP_MedBackpack_C
; TODO : Add Heal (Same as above, a lot of stuff in the folder)
RAKE=/Game/Wildfire/Blueprints/Core/Items/Rake/BP_Rake.BP_Rake_C
WATERSHIELD=/Game/Wildfire/Blueprints/Core/Items/WaterShield/BP_WaterShield.BP_WaterShield_C
WINCH=/Game/Wildfire/Blueprints/Core/Items/Winch/BP_WInchEnd.BP_WInchEnd_C 
;Not a typo, its WInch in the actual path
CONE=/Game/Wildfire/StaticMeshes/Props/Tools/S_Cone.S_Cone
WARN=/Game/Wildfire/StaticMeshes/Props/Tools/S_FirefighterWarningSign.S_FirefighterWarningSign

; Characters
CIVIL=/Game/Wildfire/Blueprints/Core/Characters/Civilians/BP_Civil.BP_Civil_C
CIVILHANA=/Game/Wildfire/Blueprints/Core/Characters/Civilians/BP_Civil_Hana.BP_Civil_Hana_C
CIVILTREY=/Game/Wildfire/Blueprints/Core/Characters/Civilians/BP_Civil_Trey.BP_Civil_Trey_C
CIVILVIVI=/Game/Wildfire/Blueprints/Core/Characters/Civilians/BP_Civil_Vivi.BP_Civil_Vivi_C
FIREFIGHTER=/Game/Wildfire/Blueprints/Core/Characters/Firefighters/BP_Firefighter.BP_Firefighter_C
FIREFIGHTERTEAMMATE=/Game/Wildfire/Blueprints/Core/Characters/Firefighters/BP_Teammate.BP_Teammate_C

;WTF IS THIS DOING IN CHARACTERS SECTION ?
STRETCHER=/Game/Wildfire/Blueprints/Core/Props/Medical/BP_Stretcher.BP_Stretcher_C 

[Settings]
; Settings for the script (Disable/Enable features)
; TODO : Implement these settings in the main.lua

DEBUG_MODE=true

[Keybinds]
; Keyboard shortcuts. Use UE4SS key names such as F1, F2, F5, F6, F7.
PlayerCheatKey=F1
NoClipKey=F2
WorldBoundariesKey=F5
EntityOutlineKey=F6
GodModeKey=F7
CollisionKey=F8
EntitySelectorKey=F9
